import { createHash } from "node:crypto";
import { getPrisma } from "../domain-intelligence/prisma.ts";
import { getContinuousDiscoveryService } from "../continuous-discovery/service.ts";

const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const page = (value?: number, maximum = 100) => Math.max(1, Math.min(maximum, Math.trunc(value ?? 25)));

export class OpportunityMonitoringService {
  private db = getPrisma();
  async start(input: { domainId: string; priority?: number; force?: boolean }) {
    const [domain, scores, changes] = await Promise.all([this.db.domain.findUnique({ where: { id: input.domainId } }), this.db.companyScore.findMany({ where: { domainId: input.domainId }, orderBy: { scoredAt: "desc" } }), this.db.companyChange.findMany({ where: { companyId: { in: (await this.db.companyScore.findMany({ where: { domainId: input.domainId }, select: { companyId: true } })).map(x => x.companyId) } }, orderBy: { detectedAt: "desc" }, take: 100 })]);
    if (!domain) throw new Error("Domain not found"); const inputHash = hash([domain.updatedAt, scores.map(s => [s.companyId, s.buyerScore, s.confidenceScore, s.scoredAt]), changes.map(c => [c.id, c.detectedAt])]);
    const previous = await this.db.monitoringJob.findFirst({ where: { domainId: input.domainId, inputHash, status: "COMPLETED" }, orderBy: { completedAt: "desc" } });
    if (previous && !input.force) return { ...previous, cached: true };
    const job = await this.db.monitoringJob.create({ data: { domainId: input.domainId, inputHash, priority: input.priority ?? 50 } });
    await this.db.monitoringHistory.create({ data: { monitoringJobId: job.id, event: "QUEUED", details: { inputHash } } }); return job;
  }
  async run(id: string) {
    let job = await this.db.monitoringJob.update({ where: { id }, data: { status: "RUNNING", startedAt: new Date(), progress: 10 } });
    try {
      const scan = await getContinuousDiscoveryService().start(job.domainId, job.priority); await this.db.monitoringJob.update({ where: { id }, data: { scanJobId: scan.id, progress: 25 } }); await getContinuousDiscoveryService().process(scan.id);
      const scores = await this.db.companyScore.findMany({ where: { domainId: job.domainId }, include: { company: true }, orderBy: { buyerScore: "desc" } });
      for (const score of scores.filter(s => s.buyerScore >= 60)) { const reason = score.buyerScore >= 80 ? `${score.company.name} is a high-priority buyer with a ${score.buyerScore}/100 fit.` : `${score.company.name} meets the qualified buyer threshold.`; const opportunity = await this.db.opportunity.upsert({ where: { domainId_companyId_type_inputHash: { domainId: job.domainId, companyId: score.companyId, type: "BUYER_MATCH", inputHash: hash([job.inputHash, score.companyId, score.buyerScore]) } }, create: { domainId: job.domainId, companyId: score.companyId, type: "BUYER_MATCH", inputHash: hash([job.inputHash, score.companyId, score.buyerScore]), score: score.buyerScore, confidence: score.confidenceScore, priority: score.buyerScore >= 80 ? "HIGH" : "MEDIUM", reason, evidence: { matchReason: score.matchReason, scoredAt: score.scoredAt } }, update: { score: score.buyerScore, confidence: score.confidenceScore, reason } }); if (score.buyerScore >= 80) await this.alert("HIGH_PRIORITY_BUYER", job.domainId, score.companyId, opportunity.id, "High-priority buyer", reason, "HIGH"); }
      await this.generateRecommendations(job.domainId); await this.captureTrends(job.domainId);
      job = await this.db.monitoringJob.update({ where: { id }, data: { status: "COMPLETED", progress: 100, completedAt: new Date() } }); await this.alert("MONITORING_COMPLETED", job.domainId, null, null, "Monitoring completed", "The latest public intelligence cycle completed successfully.", "INFO"); await this.db.monitoringHistory.create({ data: { monitoringJobId: id, event: "COMPLETED", details: { scanJobId: job.scanJobId } } }); return job;
    } catch (error) { const message = error instanceof Error ? error.message : "Monitoring failed"; await this.db.monitoringJob.update({ where: { id }, data: { status: "FAILED", error: message, completedAt: new Date() } }); await this.alert("MONITORING_FAILURE", job.domainId, null, null, "Monitoring failed", message, "ERROR"); throw error; }
  }
  async stop(id: string) { const job = await this.db.monitoringJob.findUniqueOrThrow({ where: { id } }); if (job.scanJobId) await getContinuousDiscoveryService().cancel(job.scanJobId).catch(() => undefined); return this.db.monitoringJob.update({ where: { id }, data: { status: "CANCELLED", completedAt: new Date() } }); }
  status(id?: string) { return id ? this.db.monitoringJob.findUnique({ where: { id } }) : this.db.monitoringJob.findMany({ orderBy: { requestedAt: "desc" }, take: 50 }); }
  opportunities(input: { domainId?: string; priority?: string; take?: number; cursor?: string }) { return this.db.opportunity.findMany({ where: { domainId: input.domainId, priority: input.priority, status: "OPEN" }, orderBy: [{ score: "desc" }, { detectedAt: "desc" }], take: page(input.take) + 1, ...(input.cursor ? { cursor: { id: input.cursor }, skip: 1 } : {}) }); }
  recommendations(input: { domainId?: string; take?: number }) { return this.db.recommendation.findMany({ where: { domainId: input.domainId }, orderBy: [{ score: "desc" }, { createdAt: "desc" }], take: page(input.take) }); }
  alerts(input: { unread?: boolean; take?: number }) { return this.db.alert.findMany({ where: input.unread ? { readAt: null } : undefined, orderBy: { createdAt: "desc" }, take: page(input.take) }); }
  async preferences(items: Array<{ alertType: string; inApp?: boolean; email?: boolean; threshold?: number }>) { for (const item of items) await this.db.alertPreference.upsert({ where: { alertType: item.alertType }, create: { alertType: item.alertType, inApp: item.inApp ?? true, email: item.email ?? false, threshold: item.threshold }, update: { inApp: item.inApp, email: item.email, threshold: item.threshold } }); return this.db.alertPreference.findMany({ orderBy: { alertType: "asc" } }); }
  trends(domainId?: string) { return this.db.trendSnapshot.findMany({ where: { domainId }, orderBy: { capturedAt: "desc" }, take: 90 }); }
  async rule(input: { domainId: string; frequency?: string; priority?: number; ignoredIndustries?: string[]; ignoredCountries?: string[]; minimumBuyerScore?: number; minimumConfidence?: number; maximumConcurrentJobs?: number; notificationPreferences?: unknown; nextRunAt?: string }) { const nextRunAt = input.nextRunAt ? new Date(input.nextRunAt) : new Date(); return this.db.monitoringRule.upsert({ where: { domainId: input.domainId }, create: { domainId: input.domainId, frequency: input.frequency ?? "DAILY", priority: input.priority ?? 50, ignoredIndustries: input.ignoredIndustries ?? [], ignoredCountries: input.ignoredCountries ?? [], minimumBuyerScore: input.minimumBuyerScore ?? 60, minimumConfidence: input.minimumConfidence ?? 50, maximumConcurrentJobs: input.maximumConcurrentJobs ?? 2, notificationPreferences: (input.notificationPreferences ?? { inApp: true, email: false }) as object, nextRunAt }, update: { frequency: input.frequency, priority: input.priority, ignoredIndustries: input.ignoredIndustries, ignoredCountries: input.ignoredCountries, minimumBuyerScore: input.minimumBuyerScore, minimumConfidence: input.minimumConfidence, maximumConcurrentJobs: input.maximumConcurrentJobs, notificationPreferences: input.notificationPreferences as object | undefined, nextRunAt } }); }
  rules() { return this.db.monitoringRule.findMany({ orderBy: { nextRunAt: "asc" } }); }
  private async generateRecommendations(domainId: string) { const opportunities = await this.db.opportunity.findMany({ where: { domainId, status: "OPEN" }, orderBy: { score: "desc" }, take: 20 }); for (const opportunity of opportunities.slice(0, 5)) { const inputHash = hash([opportunity.id, opportunity.updatedAt]); await this.db.recommendation.upsert({ where: { type_inputHash: { type: "CONTACT_PRIORITY", inputHash } }, create: { domainId, companyId: opportunity.companyId, type: "CONTACT_PRIORITY", inputHash, score: opportunity.score, title: "Contact this buyer first", explanation: opportunity.reason, suggestedActions: ["Review public company profile", "Verify decision-maker contact", "Generate a personalized outreach draft"], evidence: opportunity.evidence as object }, update: { score: opportunity.score, explanation: opportunity.reason } }); } }
  private async captureTrends(domainId: string) { const scores = await this.db.companyScore.findMany({ where: { domainId }, include: { company: { include: { industries: { include: { industry: true } } } } } }); const industries: Record<string, number> = {}, countries: Record<string, number> = {}; for (const score of scores) { for (const row of score.company.industries) industries[row.industry.name] = (industries[row.industry.name] ?? 0) + 1; const country = score.company.country ?? "Unknown"; countries[country] = (countries[country] ?? 0) + 1; } return this.db.trendSnapshot.create({ data: { domainId, period: new Date().toISOString().slice(0, 10), metrics: { buyerCount: scores.length, averageScore: scores.length ? Math.round(scores.reduce((sum, score) => sum + score.buyerScore, 0) / scores.length) : 0, industries, countries } } }); }
  private async alert(type: string, domainId: string | null, companyId: string | null, opportunityId: string | null, title: string, message: string, severity: string) { const preference = await this.db.alertPreference.findUnique({ where: { alertType: type } }); if (preference && !preference.inApp) return; const alert = await this.db.alert.create({ data: { type, domainId, companyId, opportunityId, title, message, severity, data: {} } }); await this.db.notificationHistory.create({ data: { alertId: alert.id, channel: "IN_APP", status: "DELIVERED" } }); }
}
let service: OpportunityMonitoringService | undefined; export const getOpportunityMonitoringService = () => service ??= new OpportunityMonitoringService();
