"use client";
import { useState } from "react";

type Mode = "valuation" | "buyers" | "outreach" | "negotiation" | "analytics";
export function IntelligenceWorkspace({ mode }: { mode: Mode }) {
  const [domainId, setDomainId] = useState(""); const [data, setData] = useState<unknown>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function run() { setBusy(true); setError(""); try { let url = ""; let init: RequestInit = {}; if (mode === "valuation") { url = "/api/valuation/run"; init = { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ domainId }) }; } if (mode === "buyers") url = `/api/buyers/rankings?domainId=${encodeURIComponent(domainId)}`; if (mode === "negotiation") { url = "/api/negotiation/generate"; init = { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ domainId }) }; } if (mode === "analytics") url = `/api/analytics/domain/${encodeURIComponent(domainId)}`; if (mode === "outreach") url = "/api/outreach/templates"; const response = await fetch(url, init); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Request failed"); setData(result); } catch (cause) { setError(cause instanceof Error ? cause.message : "Request failed"); } finally { setBusy(false); } }
  return <section className="intelligence-panel"><div className="analysis-form"><label htmlFor="domain-id">Domain ID</label><div><input id="domain-id" value={domainId} onChange={(event) => setDomainId(event.target.value)} placeholder={mode === "outreach" ? "Optional for template library" : "Paste an analyzed domain ID"}/><button onClick={run} disabled={busy || (mode !== "outreach" && !domainId)}>{busy ? "Working…" : mode === "outreach" ? "Load templates" : "Generate report"}</button></div></div>{error && <p className="form-error">{error}</p>}{data ? <pre className="report-json">{JSON.stringify(data, null, 2)}</pre> : <div className="empty-inline"><strong>Ready when you are</strong><p>Use an analyzed domain ID to generate current intelligence.</p></div>}</section>;
}
