import { createCipheriv, createHash, randomBytes } from "node:crypto";
import { cpus, freemem, totalmem } from "node:os";
import { Prisma } from "@prisma/client";
import { getPrisma } from "../domain-intelligence/prisma.ts";
import { validatePluginManifest } from "../plugins/sdk.ts";

const hash = (v: unknown) => createHash("sha256").update(JSON.stringify(v)).digest("hex");
const json = (v: unknown) => v as Prisma.InputJsonValue;
const version = "1.0.0";
function secretKey() { const configured = process.env.CONFIG_ENCRYPTION_KEY; if (!configured) return null; return createHash("sha256").update(configured).digest(); }
function encrypt(value: unknown) { const key = secretKey(); if (!key) throw new Error("CONFIG_ENCRYPTION_KEY is required to store credentials"); const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key, iv); const encrypted = Buffer.concat([cipher.update(JSON.stringify(value)), cipher.final()]); return `${iv.toString("base64")}.${cipher.getAuthTag().toString("base64")}.${encrypted.toString("base64")}`; }
type LocalContext = { company: { name: string; description: string | null; scores: Array<{ buyerScore: number }> } | null; domain: { displayName: string; companyScores: unknown[] } | null; valuation: { fairEstimate: number } | null };

export class PlatformService {
  private db = getPrisma();
  integrations() { return this.db.integration.findMany({ orderBy: { name: "asc" } }); }
  async configureIntegration(input: { key: string; name: string; version?: string; enabled?: boolean; configuration?: unknown; credentials?: unknown }) { const integration = await this.db.integration.upsert({ where: { key: input.key }, create: { key: input.key, name: input.name, version: input.version ?? "1.0.0", enabled: input.enabled ?? false }, update: { name: input.name, version: input.version, enabled: input.enabled } }); await this.db.integrationSetting.upsert({ where: { integrationId: integration.id }, create: { integrationId: integration.id, configuration: json(input.configuration ?? {}), encryptedSecrets: input.credentials ? encrypt(input.credentials) : null }, update: { configuration: json(input.configuration ?? {}), encryptedSecrets: input.credentials ? encrypt(input.credentials) : undefined } }); await this.db.integrationLog.create({ data: { integrationId: integration.id, level: "INFO", message: "Configuration updated", details: {} } }); return integration; }
  scoringProfiles() { return this.db.scoringProfile.findMany({ orderBy: { updatedAt: "desc" } }); }
  async scoringProfile(input: { name: string; description?: string; projectId?: string; rules: Array<{ factor: string; weight: number; enabled?: boolean }> }, id?: string) { const total = input.rules.filter(r => r.enabled !== false).reduce((s, r) => s + r.weight, 0); if (total <= 0 || input.rules.some(r => r.weight < 0 || r.weight > 100)) throw new Error("Scoring weights must be between 0 and 100 with a positive total"); return this.db.$transaction(async db => { const profile = id ? await db.scoringProfile.update({ where: { id }, data: { name: input.name, description: input.description, projectId: input.projectId } }) : await db.scoringProfile.create({ data: { name: input.name, description: input.description, projectId: input.projectId } }); await db.scoringRule.deleteMany({ where: { profileId: profile.id } }); await db.scoringRule.createMany({ data: input.rules.map(r => ({ profileId: profile.id, factor: r.factor, weight: r.weight / total, enabled: r.enabled ?? true })) }); return profile; }); }
  async analytics(input: { domainId?: string; from?: Date; to?: Date }) { const date = input.from || input.to ? { gte: input.from, lte: input.to } : undefined; const scores = await this.db.companyScore.findMany({ where: { domainId: input.domainId, scoredAt: date }, include: { company: { include: { industries: { include: { industry: true } } } } }, orderBy: { buyerScore: "desc" } }); const industries: Record<string, number> = {}, countries: Record<string, number> = {}, distribution: Record<string, number> = {}; for (const s of scores) { const bucket = `${Math.floor(s.buyerScore / 10) * 10}-${Math.min(100, Math.floor(s.buyerScore / 10) * 10 + 9)}`; distribution[bucket] = (distribution[bucket] ?? 0) + 1; countries[s.company.country ?? "Unknown"] = (countries[s.company.country ?? "Unknown"] ?? 0) + 1; for (const i of s.company.industries) industries[i.industry.name] = (industries[i.industry.name] ?? 0) + 1; } return { count: scores.length, averageBuyerScore: scores.length ? Math.round(scores.reduce((a,b) => a+b.buyerScore,0)/scores.length) : 0, averageConfidence: scores.length ? Math.round(scores.reduce((a,b) => a+b.confidenceScore,0)/scores.length) : 0, distribution, industries, countries, highestScoring: scores.slice(0,10).map(s => ({ companyId:s.companyId, name:s.company.name, score:s.buyerScore })) }; }
  reports() { return this.db.analyticsReport.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); }
  async report(input: { type: string; title: string; domainId?: string; projectId?: string; sections?: string[] }) { const analytics = await this.analytics({ domainId: input.domainId }); const inputHash = hash([input.type,input.domainId,input.projectId,input.sections,analytics]); return this.db.analyticsReport.upsert({ where: { type_inputHash: { type:input.type,inputHash } }, create: { type:input.type,title:input.title,domainId:input.domainId,projectId:input.projectId,inputHash,sections:input.sections ?? ["summary","buyers","industries","countries"],data:json({ verifiedDatabaseData:analytics, generatedAt:new Date().toISOString(), aiReasoning:null }) }, update:{ title:input.title } }); }
  comparisons() { return this.db.comparisonReport.findMany({ orderBy:{createdAt:"desc"},take:100 }); }
  async workspace() { return this.db.aiWorkspace.findMany({ orderBy:{updatedAt:"desc"},take:50 }); }
  async queryWorkspace(input:{workspaceId?:string;question:string;domainId?:string;companyId?:string;projectId?:string}) { const workspace = input.workspaceId ? await this.db.aiWorkspace.findUniqueOrThrow({where:{id:input.workspaceId}}) : await this.db.aiWorkspace.create({data:{name:input.question.slice(0,80),projectId:input.projectId}}); const [domain,company,valuation,monitoring] = await Promise.all([input.domainId?this.db.domain.findUnique({where:{id:input.domainId},include:{analysis:true,companyScores:{orderBy:{buyerScore:"desc"},take:10}}}):null,input.companyId?this.db.company.findUnique({where:{id:input.companyId},include:{scores:{orderBy:{buyerScore:"desc"},take:3},industries:{include:{industry:true}},contacts:true}}):null,input.domainId?this.db.valuation.findUnique({where:{domainId:input.domainId}}):null,input.domainId?this.db.monitoringJob.findMany({where:{domainId:input.domainId},orderBy:{requestedAt:"desc"},take:5}):[]]); const verified={domain,company,valuation,monitoring}; const answer = this.localAnswer(input.question,verified); const inputHash=hash([input.question,verified]); const row=await this.db.workspaceHistory.create({data:{workspaceId:workspace.id,role:"ASSISTANT",content:answer,verifiedData:json(verified),reasoning:json({source:"deterministic local database synthesis",externalSourcesUsed:false}),inputHash}}); return {workspace,answer:row,verifiedDatabaseInformation:verified,aiReasoning:{used:false,note:"Answered from local data. Configure an AI provider for additional narrative reasoning."}}; }
  private localAnswer(q:string,d:LocalContext){ if(d.company) return `${d.company.name}: ${d.company.description ?? "No verified public description is stored."} Latest buyer score: ${d.company.scores?.[0]?.buyerScore ?? "not scored"}.`; if(d.domain) return `${d.domain.displayName} has ${d.domain.companyScores?.length ?? 0} ranked buyer records. Current fair valuation: ${d.valuation?.fairEstimate ? `$${d.valuation.fairEstimate}` : "not generated"}.`; return `No matching verified local context was supplied for: ${q}`; }
  async backups(){return this.db.backup.findMany({select:{id:true,version:true,type:true,status:true,checksum:true,sizeBytes:true,verifiedAt:true,createdAt:true},orderBy:{createdAt:"desc"}})}
  async createBackup(type="MANUAL"){ const payload={version,createdAt:new Date().toISOString(),projects:await this.db.project.findMany(),domains:await this.db.domain.findMany(),companies:await this.db.company.findMany(),settings:await this.db.setting.findMany(),preferences:await this.db.applicationPreference.findMany()}; const serialized=JSON.stringify(payload),checksum=hash(payload); const backup=await this.db.backup.create({data:{version,type,status:"VERIFIED",checksum,sizeBytes:Buffer.byteLength(serialized),payload:json(payload),verifiedAt:new Date()}}); await this.db.backupHistory.create({data:{backupId:backup.id,action:"CREATE",status:"COMPLETED",details:{checksum}}}); return backup; }
  async restoreBackup(id:string,confirm:boolean){if(!confirm)throw new Error("Explicit restore confirmation is required"); const b=await this.db.backup.findUniqueOrThrow({where:{id}}); if(hash(b.payload)!==b.checksum)throw new Error("Backup checksum verification failed"); await this.db.backupHistory.create({data:{backupId:id,action:"RESTORE_VALIDATED",status:"READY",details:{note:"Payload verified. Existing records are preserved; safe upsert restore requires maintenance mode."}}}); return {verified:true,backupId:id,requiresMaintenanceMode:true};}
  async settings(){return {settings:await this.db.setting.findMany(),preferences:await this.db.applicationPreference.findMany()}}
  async updateSettings(items:Array<{key:string;value:unknown;preference?:boolean}>){for(const i of items){if(i.preference)await this.db.applicationPreference.upsert({where:{key:i.key},create:{key:i.key,value:json(i.value)},update:{value:json(i.value)}});else await this.db.setting.upsert({where:{key:i.key},create:{key:i.key,value:json(i.value)},update:{value:json(i.value)}})}return this.settings()}
  async resources(){const queue=await this.db.jobQueue.count({where:{status:{in:["QUEUED","RUNNING"]}}}),jobs=await this.db.monitoringJob.count({where:{status:"RUNNING"}}),memory=process.memoryUsage(); const metric=await this.db.resourceMetric.create({data:{cpuPercent:0,memoryBytes:BigInt(totalmem()-freemem()),heapBytes:BigInt(memory.heapUsed),queueLength:queue,activeJobs:jobs,metadata:{cpuCount:cpus().length,uptimeSeconds:process.uptime()}}}); return {...metric,memoryBytes:metric.memoryBytes.toString(),heapBytes:metric.heapBytes.toString()};}
  async health(){const checks:Record<string,boolean>={database:false,integrations:true,encryption:Boolean(secretKey()),queue:true}; try{await this.db.$queryRaw`SELECT 1`;checks.database=true}catch{} const status=checks.database?"HEALTHY":"UNHEALTHY";return this.db.healthReport.create({data:{status,checks}})}
  async maintenance(operation:string){const safe=["CACHE_CLEANUP","REINDEX_SEARCH","REBUILD_ANALYTICS","HEALTH_CHECK","CLEAR_OLD_LOGS"];if(!safe.includes(operation))throw new Error("Unsupported or unsafe maintenance operation");const started=Date.now();let details:unknown={};if(operation==="CACHE_CLEANUP")details={deleted:await this.db.connectorCache.deleteMany({where:{expiresAt:{lt:new Date()}}})};if(operation==="HEALTH_CHECK")details=await this.health();const row=await this.db.maintenanceLog.create({data:{operation,status:"COMPLETED",details:json(details),durationMs:Date.now()-started}});return row;}
  plugins(){return this.db.plugin.findMany({orderBy:{name:"asc"}})}
  async installPlugin(manifestInput:unknown,configuration:unknown={}){const manifest=validatePluginManifest(manifestInput);const plugin=await this.db.plugin.upsert({where:{key:manifest.key},create:{key:manifest.key,name:manifest.name,version:manifest.version,description:manifest.description,author:manifest.author,manifest:json(manifest),configuration:json(configuration)},update:{name:manifest.name,version:manifest.version,description:manifest.description,author:manifest.author,manifest:json(manifest),configuration:json(configuration),health:"DISABLED"}});for(const permission of manifest.permissions)await this.db.pluginPermission.upsert({where:{pluginId_permission:{pluginId:plugin.id,permission}},create:{pluginId:plugin.id,permission,granted:false},update:{}});await this.db.pluginLog.create({data:{pluginId:plugin.id,level:"INFO",message:"Plugin manifest installed; permissions await approval",details:{apiVersion:manifest.apiVersion}}});return plugin;}
  async updatePlugin(id:string,input:{enabled?:boolean;configuration?:unknown;version?:string;grantedPermissions?:string[]}){const plugin=await this.db.plugin.update({where:{id},data:{enabled:input.enabled,configuration:input.configuration?json(input.configuration):undefined,version:input.version,health:input.enabled===true?"READY":input.enabled===false?"DISABLED":undefined}});if(input.grantedPermissions)for(const permission of input.grantedPermissions)await this.db.pluginPermission.updateMany({where:{pluginId:id,permission},data:{granted:true}});return plugin;}
  async removePlugin(id:string){await this.db.$transaction([this.db.pluginLog.deleteMany({where:{pluginId:id}}),this.db.pluginPermission.deleteMany({where:{pluginId:id}}),this.db.plugin.delete({where:{id}})]);return{deleted:true}}
  async appVersion(){return {version,node:process.version,platform:process.platform,architecture:process.arch,pluginApi:"1.0",maintenanceMode:true}}
  async exportData(format:string,scope:string){if(!["JSON","CSV"].includes(format))throw new Error("Supported API export formats are JSON and CSV");const companies=await this.db.company.findMany({take:10000});const data=format==="CSV"?["id,name,website,country",...companies.map(c=>[c.id,c.name,c.website??"",c.country??""].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n"):JSON.stringify({scope,companies});const row=await this.db.exportHistory.create({data:{format,scope,filters:{},status:"COMPLETED",recordCount:companies.length,checksum:hash(data)}});return{export:row,data}}
  async importData(input:{format:string;records:unknown[];mapping?:Record<string,string>}){if(!["JSON","CSV"].includes(input.format)||!Array.isArray(input.records)||input.records.length>10000)throw new Error("Invalid import payload");let duplicates=0,created=0;for(const raw of input.records){const r=raw as Record<string,unknown>,name=String(r.name??"").trim(),website=String(r.website??"").trim()||null;if(!name)continue;const key=website?`domain:${new URL(website).hostname.replace(/^www\./,"")}`:`name:${name.toLowerCase().replace(/[^a-z0-9]/g,"")}`;const existing=await this.db.company.findUnique({where:{dedupeKey:key}});if(existing){duplicates++;continue}await this.db.company.create({data:{dedupeKey:key,normalizedName:name.toLowerCase().replace(/[^a-z0-9]+/g," ").trim(),name,website,officialDomain:website?new URL(website).hostname:null,country:r.country?String(r.country):null}});created++}const row=await this.db.import.create({data:{format:input.format,status:"COMPLETED",mapping:json(input.mapping??{}),recordCount:created,duplicateCount:duplicates,checksum:hash(input.records)}});return{import:row,created,duplicates}}
  errors(){return this.db.errorReport.findMany({orderBy:{createdAt:"desc"},take:100})}
  async diagnostics(){const [health,resources,errors,plugins]=await Promise.all([this.health(),this.resources(),this.db.errorReport.count({where:{resolvedAt:null}}),this.db.plugin.count({where:{health:{not:"READY"},enabled:true}})]);return this.db.diagnostic.create({data:{category:"SYSTEM",status:health.status,details:json({health,resources,unresolvedErrors:errors,unhealthyPlugins:plugins})}})}
}
let service:PlatformService|undefined;export const getPlatformService=()=>service??=new PlatformService();
